
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace Package1 {
	public class Position : IMonitoredEntity {
		[Key]
		public virtual int Id {
			get;
			set;
		}

		public virtual int HeaderId {
			get;
			set;
		}

		public virtual string Description {
			get;
			set;
		}

		public virtual int SequenceNumber {
			get;
			set;
		}

		// Implementation of IMonitoredEntity
		public virtual DateTime DateCreated { get;set; }

		public virtual DateTime DateModified { get;set; }

		// association properties
		public virtual Header Header {
			get;
			set;
		}

	}
}
#pragma warning restore 1591
